# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dipcord

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dipcord.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fce65dd88e864b4fa23e0182145228d6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_97fa6ee275684a139f635087564a0c58 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dipcord.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fce65dd88e864b4fa23e0182145228d6 }}/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dipcord'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de7265c54f404b4eb9e6cfb59181cfc4 }}
        images: 'dipcord.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fce65dd88e864b4fa23e0182145228d6 }}/webimage:${{ github.sha }}'