on: [push]
name: "Build and Deploy to Azure Container Instances"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
            username: ${{ vars.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ vars.REGISTRY_LOGIN_SERVER }}/webimage:${{ github.sha }}
            docker push ${{ vars.REGISTRY_LOGIN_SERVER }}/webimage:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ vars.RESOURCE_GROUP }}
            dns-name-label: ${{ vars.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ vars.REGISTRY_LOGIN_SERVER }}/webimage:${{ github.sha }}
            registry-login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ vars.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: dipcord
            location: 'west europe'